# Generated by Django 2.1.7 on 2019-05-29 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_adm', models.DateField(default=datetime.date(2019, 5, 29))),
                ('date_of_discarge', models.DateField()),
                ('diagnosis', models.ForeignKey(on_delete=None, to='hospital.Diagnose')),
                ('doctor', models.ForeignKey(on_delete=None, to='staff.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Out_patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 5, 29))),
                ('diagnosis', models.ForeignKey(on_delete=None, to='hospital.Diagnose')),
                ('doctor', models.ForeignKey(on_delete=None, to='staff.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(default=0, max_length=15)),
                ('age', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='out_patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient'),
        ),
        migrations.AddField(
            model_name='in_patient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient'),
        ),
        migrations.AddField(
            model_name='in_patient',
            name='room',
            field=models.ForeignKey(on_delete=None, to='hospital.Room'),
        ),
    ]
