# Generated by Django 2.1.7 on 2019-05-29 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('hospital', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 5, 29))),
                ('symptoms', models.TextField()),
                ('doctors_comments', models.TextField()),
                ('diagnosis', models.ForeignKey(on_delete=None, to='hospital.Diagnose')),
                ('doctor', models.ForeignKey(on_delete=None, to='staff.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.Patient')),
            ],
        ),
    ]
